### ISSUE TITLE
not workine

### ISSUE THREAD

**Issue by noelmaher** [PocketMine/PocketMine-Android#20]

**Comment by noelmaher** [comment]
I've installed the latest stable release on an android device and I'm trying to connect from minecraft pe 0.9.5. However I keep getting an error saying could not connect: outdated server. Does pocketmine work with pe version 0.9.5?

**Comment by shoghicp** [comment]
It does. Use a different channel than the stable channel

**Comment by noelmaher** [comment]
I tried the older alpha version and that works fine. Thanks for your help.
