### ISSUE TITLE
Help when I try going on my server it says locating server and doesnt load

### ISSUE THREAD

**Issue by Watzup14MC** [PocketMine/PocketMine-Android#23]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 01:17:58 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 01:17:59 [WARNING] Non-packaged PocketMine-MP installation detected, do not use on production.
[Server] 01:17:59 [INFO] Starting Minecraft: PE server version v0.10.4 alpha
[Server] 01:17:59 [INFO] Loading pocketmine.yml...
[Server] 01:17:59 [INFO] Loading server properties...
[Server] 01:17:59 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 01:17:59 [INFO] This server is running PocketMine-MP version 1.4dev-913 "絶好(Zekkou)ケーキ(Cake)" (API 1.10.0)
[Server] 01:17:59 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 01:18:00 [CRITICAL] ***\* FAILED TO BIND TO 0.0.0.0:19132!
[Server] 01:18:00 [CRITICAL] Perhaps a server is already running on that port?
[Server] 01:18:00 [EMERGENCY] [RakLib Thread #1077968168] RakLib crashed!
[Server] 01:18:06 [INFO] Preparing level "world"
[Server] 01:18:07 [INFO] Starting GS4 status listener
[Server] 01:18:07 [INFO] Setting query port to 19132
[Server] 01:18:07 [INFO] Query running on 0.0.0.0:19132
[Server] 01:18:08 [INFO] Default game type: SURVIVAL
[Server] 01:18:08 [INFO] Done (14.997s)! For help, type "help" or "?"
[PocketMine] Stopping server...
[Server] 01:19:26 [INFO] CONSOLE: Stopping the server...
[Server] 01:19:26 [INFO] Unloading level "world"
[Server] 01:19:26 [INFO] Stopping other threads
[PocketMine] Server was stopped.

**Comment by shoghicp** [comment]
This is not a support forum.

It seems like this is entirely your problem, please close Minecraft completely before starting a server.
