### ISSUE TITLE
Doesn't work on my device...

### ISSUE THREAD

**Issue by Redshif1** [PocketMine/PocketMine-Android#27]
I am running Android 5.0 on a Nextbook 8 Ares and the model number is NXA8QC116... Please fix!!!!! 😧

When I open the app it goes to the loading screen as usual... Then I set up my server and then I go to start it... Just stops for no reason... So I look in the console and it says starting serfer. Then a line down it says stopping server or something like that. So I don't know what the issue is....

**Comment by shoghicp** [comment]
Maybe you are running out of memory!

This seems to be an issue with your configuration.
