### ISSUE TITLE
Hello PocketMine Team

### ISSUE THREAD

**Issue by miyu-desu** [PocketMine/PocketMine-Android#38]
Hello, I want to hangeul my pocket language with the titles of the titles.
There are a large number of Korean pocket users!
I don't know English very well those who choose the direction can be used to distribute jokesseumni....
Fly Omni see a lot of questions many people who can't speak English....
So I pocket Mine Korean. May I ask you, the distribution....

Here's your download link.
pocketmine.f4m.kr

If there is a download error, please look at the 1.0.1.

**Comment by hiilikewiki** [comment]
Please use the new PMMP
