### ISSUE TITLE
Two whitelist settings in server.properties page

### ISSUE THREAD

**Issue by billym357** [PocketMine/PocketMine-Android#5]
I don't know if I had both turned on or not but I know at least one was set to on and a non whitelisted player was able to join. I now have both turned on and the player wasn't able to join.

**Comment by PEMapModder** [comment]
Which two?

Refer to the wiki.

**Comment by billym357** [comment]
What do you mean which two? There should only be one whitelist setting on the server.properties page.

Edit: File not page
