### ISSUE TITLE
PocketMine-MP 1.4 Alpha not work!

### ISSUE THREAD

**Issue by LucaPensabene** [PocketMine/PocketMine-Android#6]
I have this error:

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 
[Server] Warning: require_once(/storage/emulated/0/PocketMine/src/config.php): failed to open stream: No such file or directory in /storage/emulated/0/PocketMine/PocketMine-MP.php on line 24
[Server] 
[Server] Fatal error: require_once(): Failed opening required '/storage/emulated/0/PocketMine/src/config.php' (include_path='.:') in /storage/emulated/0/PocketMine/PocketMine-MP.php on line 24
[PocketMine] Server was stopped.

Can you fix it? Thanks!

**Comment by PEMapModder** [comment]
Android does not support 1.4 yet
