### ISSUE TITLE
FIX THIS NOW PLZ.

### ISSUE THREAD

**Issue by fallendestiny42** [PocketMine/PocketMine-Android#7]
I use the latest version, 1.3.12 , and it says something like: fatal error in opening pocket mine.php and when I check, the file is empty. Why aren't I getting the proper file??

**Comment by MCMrARM** [comment]
redownload PM from Version Manager

**Comment by fallendestiny42** [comment]
I tried that. Still didn't work. :(
I deleted the folder from the PocketMine folder and re downloaded the version  about 6 times.

**Comment by shoghicp** [comment]
It seems like you hit "Development version", that won't work with the current version of PocketMine-MP for Android. It will be updated once PocketMine-MP Alpha_1.4 is released
