### ISSUE TITLE
Bug for 1.4dev

### ISSUE THREAD

**Issue by msjyoo** [PocketMine/PocketMine-Android#8]
Moved from PocketMine-MP
Originally by hoyinm14mc

---

I use DroidPocketMine and install Alpha_1.4dev-228 beta1 but after i set all server properties and pressed "save" , it needs me to install again!! I loop this action for many times and i prefer to use back Alpha1.3.12

Please fix this problem, try use your phone to open 1.4 server then you will know what happens.

Thx! ;)

**Comment by shoghicp** [comment]
@MCMrARM is already working on this, and we generated PHP binaries for Android (@Brandon15811 is working on improved binaries with DNS and other things)
